services:
  backend:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
      - "50051:50051"
    depends_on:
      - db
    environment:
      - ENV=local
      - MIGRATIONS_PATH=/app/internal/adapters/repository/db/migrations
      - MIGRATIONS_TABLE=migrations
      - PG_USER=myuser
      - PG_PASS=mysecretpassword
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=s3_mini
      - PG_SSL_MODE=disable
      - CHUNK_SIZE=10000
      - GRPC_HOST=localhost
      - GRPC_PORT=50051

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=s3_mini
      - POSTGRES_SSLMODE=disable
